### PR TITLE
Suggested Updates to Azure KeyVault Configuration

### PR DESCRIPTION
**Pull request by cabberley**
I have made several changes to make it clearer for people to perform this setup. 
- Added cross references between values that must be collected during creation of App and Key vault and their usage in the CLI Parameters.
- Fixed a typo for the set advanced -con off Cli command
- Added a potential resolution for customers if they don't get a service_reachability "OK", the error generated by the CLI is cryptic and provides no direction to the user on what is wrong.

### CODE REVIEW

**Comment by netapp-rlithman** [comment]
Hi Chris. Thank you for taking the time to improve our documentation. I need to verify the changes with the team before taking action. I'll let you know if we have any questions or feedback.

**Comment by ntap-bmegan** [comment]
@netapp-rlithman - Can you provide an update on this PR?

**Comment by netapp-rlithman** [comment]
I am currently working with the team to review these suggested updates with others made on the same topic.

**Comment by netapp-rlithman** [comment]
Chris, we updated the page with your guidance and other feedback from the team. Thank you for reaching out. 

[Manage keys with Azure Key Vault](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-azure-key-vault.html#configuration-process)

**Pull request closed without merging**
